-- MySQL Script generated by MySQL Workbench
-- Sat Feb 15 16:21:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meubd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meubd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meubd` DEFAULT CHARACTER SET utf8 ;
USE `meubd` ;

-- -----------------------------------------------------
-- Table `meubd`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`agencia` (
  `id_agencia` INT NOT NULL AUTO_INCREMENT,
  `nome_agencia` VARCHAR(45) NOT NULL,
  `salario_total` DECIMAL(9,2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_agencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`Funcionario` (
  `id_funcionarios` INT NOT NULL,
  `id_agencia` INT NOT NULL,
  `nome_completo` VARCHAR(45) NOT NULL,
  `senha_funcionario` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `genero` ENUM('masculino', 'feminino', 'não-binario') NOT NULL,
  `data_nascimeto` DATE NOT NULL,
  `salario` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id_funcionarios`),
  INDEX `fk_Funcionario_Agência1_idx` (`id_agencia` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Agência1`
    FOREIGN KEY (`id_agencia`)
    REFERENCES `meubd`.`agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`Clientes` (
  `cpf` BIGINT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `RG` INT(15) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`telefones_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`telefones_clientes` (
  `cpf` INT(11) NOT NULL,
  `numero_telefones` INT(11) NOT NULL,
  `tipo_telefone` ENUM('telefone', 'celular1', 'residencial', 'celular2') NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_telefones_clientes_Clientes1_idx` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes_Clientes1`
    FOREIGN KEY (`cpf`)
    REFERENCES `meubd`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`Dependentes` (
  `id_dependentes` VARCHAR(45) NOT NULL,
  `id_funcionarios` INT NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `parentesco` ENUM('filho', 'conjugue', 'genitor') NOT NULL,
  PRIMARY KEY (`id_dependentes`),
  INDEX `fk_Dependentes_Funcionario1_idx` (`id_funcionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_Funcionario1`
    FOREIGN KEY (`id_funcionarios`)
    REFERENCES `meubd`.`Funcionario` (`id_funcionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`emails_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`emails_clientes` (
  `cpf` INT(11) NOT NULL,
  `tipo_email` ENUM('profissional', 'pessoal', 'comercial') NOT NULL,
  `email` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_emails_clientes_Clientes1_idx` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_emails_clientes_Clientes1`
    FOREIGN KEY (`cpf`)
    REFERENCES `meubd`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`conta_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`conta_bancaria` (
  `num_conta` INT NOT NULL,
  `id_agencia` INT NOT NULL,
  `id_funcionarios` INT NOT NULL,
  `saldo` DECIMAL(9,2) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipos_conta` ENUM('poupanca', 'corrente', 'conta especial') NOT NULL,
  `tipo_unica_conjunta` ENUM('unica', 'conjunta') NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_conta_bancaria_Agência1_idx` (`id_agencia` ASC) VISIBLE,
  INDEX `fk_conta_bancaria_Funcionario1_idx` (`id_funcionarios` ASC) VISIBLE,
  CONSTRAINT `fk_conta_bancaria_Agência1`
    FOREIGN KEY (`id_agencia`)
    REFERENCES `meubd`.`agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_bancaria_Funcionario1`
    FOREIGN KEY (`id_funcionarios`)
    REFERENCES `meubd`.`Funcionario` (`id_funcionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`transacao` (
  `id_transacao` INT NOT NULL,
  `num_conta` INT NOT NULL,
  `tipo_transacao` ENUM('depodito', 'saque', 'pagamento', 'estorno', 'PIX') NOT NULL,
  `data_hora` TIMESTAMP NULL,
  `valor` DECIMAL(9,2) NULL,
  `transacaocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_transacao`),
  UNIQUE INDEX `id_transacao_UNIQUE` (`id_transacao` ASC) VISIBLE,
  INDEX `fk_transacao_conta_bancaria1_idx` (`num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_conta_bancaria1`
    FOREIGN KEY (`num_conta`)
    REFERENCES `meubd`.`conta_bancaria` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`Conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`Conta_corrente` (
  `num_conta` INT NOT NULL,
  `data_aniv_contrato` DATE NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_Conta_corrente_conta_bancaria1_idx` (`num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_corrente_conta_bancaria1`
    FOREIGN KEY (`num_conta`)
    REFERENCES `meubd`.`conta_bancaria` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`poupanca` (
  `num_conta` INT NOT NULL,
  `taxa_juros` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_poupanca_conta_bancaria1_idx` (`num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_poupanca_conta_bancaria1`
    FOREIGN KEY (`num_conta`)
    REFERENCES `meubd`.`conta_bancaria` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`conta_especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`conta_especial` (
  `num_conta` INT NOT NULL,
  `limite_credito` DECIMAL(9,2) NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_conta_especial_conta_bancaria1_idx` (`num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_especial_conta_bancaria1`
    FOREIGN KEY (`num_conta`)
    REFERENCES `meubd`.`conta_bancaria` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`endereco_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`endereco_cliente` (
  `cpf` INT(11) NOT NULL,
  `tipo_logradouro` VARCHAR(45) NULL,
  `nome_logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `numero_casa` INT NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_endereco_cliente_Clientes1`
    FOREIGN KEY (`cpf`)
    REFERENCES `meubd`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meubd`.`conta_e_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meubd`.`conta_e_cliente` (
  `num_conta` INT NOT NULL,
  `cpf` INT(11) NOT NULL,
  PRIMARY KEY (`num_conta`, `cpf`),
  INDEX `fk_conta_bancaria_has_Clientes_Clientes1_idx` (`cpf` ASC) VISIBLE,
  INDEX `fk_conta_bancaria_has_Clientes_conta_bancaria1_idx` (`num_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_bancaria_has_Clientes_conta_bancaria1`
    FOREIGN KEY (`num_conta`)
    REFERENCES `meubd`.`conta_bancaria` (`num_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_bancaria_has_Clientes_Clientes1`
    FOREIGN KEY (`cpf`)
    REFERENCES `meubd`.`Clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
