SELECT * FROM nullbank.agencia;
SELECT * FROM nullbank.cliente;
SELECT * FROM nullbank.email;
SELECT * FROM nullbank.telefone;
SELECT * FROM nullbank.conta;
SELECT * FROM nullbank.cliente_conta;
SELECT * FROM nullbank.funcionario;
SELECT * FROM nullbank.transacao;
SELECT * FROM nullbank.dependente;